apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spring-build-ci
spec:
  containers:
    - name: maven
      image: maven:alpine
      command:
        - cat
      tty: true
      volumeMounts:
        - name: m2
          mountPath: /root/.m2/
    - name: docker-tools
      image: rmkanda/docker-tools:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /tmp/trivycache/
          name: trivycache
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.6.0-debug
      imagePullPolicy: Always
      command:
        - sleep
      args:
        - 99d
      # 1. Added environment variable so Kaniko looks for your credentials in the correct folder
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      volumeMounts:
        - name: jenkins-docker-cfg
          mountPath: /kaniko/.docker
    - name: trufflehog
      image: rmkanda/trufflehog
      command:
        - cat
      tty: true
    - name: licensefinder
      image: licensefinder/license_finder
      command:
        - cat
      tty: true
  volumes:
    # 2. Changed hostPath to emptyDir because EKS blocks hostPath for security reasons
    - name: m2
      emptyDir: {}
    - name: trivycache
      emptyDir: {}
    - name: jenkins-docker-cfg
      projected:
        sources:
          - secret:
              name: regcred
              items:
                - key: .dockerconfigjson
                  path: config.json
